version: '3.9'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: '${APP_NAME}-docker'
    restart: always
    ports:
      - '${APP_PORT}:9090'
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/srv/data/templates:/usr/share/nginx/html"
      - ./prometheus/:/etc/prometheus/